server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
  
  profiles:
    include: jwt
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel?serverTimezone=Asia/Seoul
    username: cos
    password: 19970604
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

  # 이메일 전송
  mail:
    host: smtp.gmail.com
    port: 587
    username: syhwang4223@gmail.com
    password: rylrjsathsqmeeco
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  # Redis
  redis:
    host: localhost
    port: 6379
    password:

cos:
  key: cos1234

  
#jwt:
#  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
#  token-validity-in-seconds: 86400